// today date 

let myDate= new Date();
// let myDate =Date();

// console.log(Date());
// console.log(myDate.toString());
// console.log(myDate.toDateString());
// console.log(myDate.toTimeString());
// console.log(myDate.toISOString());
// console.log(myDate.toJSON());
// console.log(myDate.toLocaleDateString());
console.log(myDate.toLocaleTimeString());
// console.log(myDate.toLocaleString());


// date creat krna 


// let creatDate= new Date(2023,0,4);//year month date
 
// console.log(creatDate.toDateString());//Wed Jan 04 2023

// let creatDate1= new Date(2023,0,4,13,13,55);// YY MM DD TIME(H M S)
// console.log(creatDate1.toLocaleString());//4/1/2023, 1:13:55 pm
// let creatDate2= new Date(2023,0,4,13,13,55);


// Dates

// let myDate = new Date()
// console.log(myDate.toString());
// console.log(myDate.toDateString());
// console.log(myDate.toLocaleString());
// console.log(typeof myDate);

// let myCreatedDate = new Date(2023, 0, 23)
// let myCreatedDate = new Date(2023, 0, 23, 5, 3)
// let myCreatedDate = new Date("2023-01-14")
// let myCreatedDate = new Date("01-14-2023")
// console.log(myCreatedDate.toLocaleString());

// let myTimeStamp = Date.now()

// console.log(myTimeStamp);
// console.log(myCreatedDate.getTime());
// console.log(Math.floor(Date.now()/1000));

// let newDate = new Date()
// console.log(newDate);
// console.log(newDate.getMonth() + 1);
// console.log(newDate.getDay());

// `${newDate.getDay()} and the time `

// newDate.toLocaleString('default', {
//     weekday: "long",
    
// })